### ISSUE TITLE
Where is the intercept of genetic covariance?

### ISSUE THREAD

**Issue by MAX-BEEN** [mglev1n/ldscr#12]
Hello!
I want to know if there is a result of intercept of genetic covariance in the ldsc_rg?  Is "I" of the "raw" list of results of ldsc_rg? 
Sincerely looking forward your reply!

**Comment by mglev1n** [comment]
This was also asked in issue #11 - not sure if @MikeKiki101 was able to make any progress exposing this variable. Happy to consider a pull request that includes this intercept in the output. Otherwise, I can plan to add in a future release/update.
