### ISSUE TITLE
Heritability Estimation Error

### ISSUE THREAD

**Issue by rachel-yd** [mglev1n/ldscr#13]
To whom it may concern, 

I am new to R and the ldscr function. I am trying to run cross-trait LDSC for two munged datasets. But I kept getting the following error message: 

**Error in t(weighted.LD[select.from[i]:select.to[i], ]) %*% weighted.chi[select.from[i]:select.to[i],  : 
  Non-integer argument 
✖Estimating heritability for 'dt1' [2.6s]**

The data input format is as required, where dt1 and dt2 are two dataframes with 10 columns (SNP, CHR, BP, A1, A2, BETA, SE, P, N, Z): 

**rg_res<-ldscr::ldsc_rg(
  munged_sumstats = list(
    "dt1"=dt1,
    "dt2"=dt2),
  ancestry="EUR")**

Is this problem occuring on my end (as in error in the data input) or the package's end? Please kindly advise! Thank you very much. 

The rest of the report is as follows: 
No sample prevalence data provided. Estimating heritabilities on the observed scale.
✔ Using EUR reference from Pan-UKB [137ms]
✔ Reading LD Scores [784ms]                                                 
✔ Reading weights [739ms]                                                   
✔ Reading M [154ms]                                                                                              
✔ Reading summary statistics for 'dt1' from dataframe [71ms]
ℹ 12/59 SNPs remain after merging 'dt1' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 80 from 'dt1'; 12 SNPs remain
✔ Merging 'dt1' with LD-score files [2.5s]
✔ Reading summary statistics for 'dt2' from dataframe [57ms]
ℹ 14/79 SNPs remain after merging 'dt2' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 377.277 from 'dt2'; 14 SNPs remain
✔ Merging 'dt2' with LD-score files [1.5s]
✔ Reading summary statistics [4.6s]
Error in t(weighted.LD[select.from[i]:select.to[i], ]) %*% weighted.chi[select.from[i]:select.to[i],  :  Non-integer argument 
✖Estimating heritability for 'dt1' [2.6s]

**Comment by mglev1n** [comment]
Without seeing `dt1` or `dt2` it is hard to provide advice. Are you able to provide a reproducible example and/or run the examples using the built-in data: https://mglev1n.github.io/ldscr/#usage

Based on the error message, it seems that one of the columns that should contain only numeric values (eg. BETA, SE, P, N, Z) may contain other types.

**Comment by guoyh22** [comment]
I have encountered the same issue. Do you have any suggestions?
+   ldsc_female <- ldsc_female[, .(SNP, N, Z, A1, A2)]
+   ldsc_male <- ldsc_male[, .(SNP, N, Z, A1, A2)]
+   # 将 N 和 Z 列转换为数值型
+   ldsc_female[, N := as.numeric(N)]
+   ldsc_female[, Z := as.numeric(Z)]
+   
+   ldsc_male[, N := as.numeric(N)]
+   ldsc_male[, Z := as.numeric(Z)]
+   h2_res <- ldsc_h2(munged_sumstats = ldsc_female , ancestry = "EUR")
+ }
✔ Using EUR reference from Pan-UKB [19ms]
✔ Reading LD Scores [168ms]                                                                             
✔ Reading weights [172ms]                                                                               
✔ Reading M [39ms]                                                                                        
✔ Reading summary statistics from dataframe [14ms]
✔ Reading summary statistics [70ms]
ℹ 168/1708 SNPs remain after merging with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 259.48; 168 SNPs remain
✔ Merging summary statistics with LD-score files [948ms]
Error in t(weighted.LD[select.from[i]:select.to[i], ]) %*% weighted.chi[select.from[i]:select.to[i],  : 
  non-conformable arguments
✖ Estimating heritability [36ms]

**Comment by mglev1n** [comment]
From the output, it appears that only 168 variants are overlapping with the LD score files, and only 1708 variants are being provided overall. LDSC is designed to work with a genome-wide set of variants (Eg. HapMap3). Are you able to provide a reproducible example and/or run the examples using the built-in data: https://mglev1n.github.io/ldscr/#usage
