### ISSUE TITLE
Abnormal genetic correlation (rg)

### ISSUE THREAD

**Issue by ahj-maker** [mglev1n/ldscr#15]
Dear Sir/Madam,

I am new to R and the ldscr function. I am trying to run cross-trait LDSC for two munged datasets. But I kept getting the following abnormal values:

Theoretically, the genetic correlation (rg) is between -1 and 1. **However, in my results, there are some cases where rg is greater than 1 or less than -1. Is this a problem with my data or a flaw in the R package?**

The data input format is as required, where dt1 and dt2 are two dataframes with 5 columns (SNP, A1, A2, N, Z):

rg_res<-ldscr::ldsc_rg(
munged_sumstats = list(
"liver"=dt1,
"immune"=dt2),
ancestry="EUR")

Please kindly advise! Thank you very much.

Best regards,

ahj

![1](https://github.com/mglev1n/ldscr/assets/152840506/49a445f5-03ee-4582-bd70-e4292ad00cf0)

**Comment by mglev1n** [comment]
These may be relevant:

https://github.com/bulik/ldsc/issues/78
https://github.com/bulik/ldsc/issues/252

**Comment by ahj-maker** [comment]
Thank you for your timely response.

**Comment by ahj-maker** [comment]
Thank you for your timely response.
