### ISSUE TITLE
 LDSCR  ,encounter a problem, the "S_Stand"not found

### ISSUE THREAD

**Issue by xuanhua612** [mglev1n/ldscr#16]
I am new, first time using the LDCSR  ,encounter a problem, the "S_Stand"not found, how to solve this problem?
details:
|==================================================|
ℹ No sample prevalence data provided. Estimating heritabilities on the observed scale.
✔ Using EUR reference from Pan-UKB [16ms]
✔ Reading LD Scores [154ms]                                                              
✔ Reading weights [152ms]                                                                
✔ Reading M [32ms]                                                                                                            
✔ Reading summary statistics for '1' from dataframe [19ms]
ℹ 964257/5586270 SNPs remain after merging '1' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 80 from '1'; 964257 SNPs remain
✔ Merging '1' with LD-score files [3.7s]
✔ Reading summary statistics for '2' from dataframe [14ms]
ℹ 1083058/11284768 SNPs remain after merging '2' with LD-score files
ℹ Removed 291 SNPs with Chi^2 > 80 from '2'; 1082767 SNPs remain
✔ Merging '2' with LD-score files [6.4s]
✔ Reading summary statistics [10.3s]
✔ Estimating heritability for '' [124ms]
✔ Estimating genetic covariance for for '' and '' [1.5s]
**! Your genetic covariance matrix includes traits estimated to have a negative heritability.
✖ Estimating heritability for '' [541ms]**
Error occurred for file: 5 
**Error message: object 'S_Stand' not found**

**Comment by mglev1n** [comment]
See https://github.com/mglev1n/ldscr/issues/8 - the genetic correlation can't be estimated since it appears one of the traits has negative heritability. This may mean that you're using small/underpowered GWAS summary statistics, or are studying traits with limited SNP heritability.

**Comment by xuanhua612** [comment]
thanks , I agree ,some pair is normal ,other have this problem,
