### ISSUE TITLE
what is 'S_Stand' ?

### ISSUE THREAD

**Issue by Libertas2017** [mglev1n/ldscr#18]
! Your genetic covariance matrix includes traits estimated to have a negative heritability.
Error: object 'S_Stand' not foundoking'

> library(ldscr)
> rg_res <- ldsc_rg(
+   munged_sumstats = list(
+     "COPD" = COPD,
+     "Smoking" = Smoking
+   ),
+   ancestry = "EUR"
+ )
ℹ No sample prevalence data provided. Estimating heritabilities on the observed scale.
✔ Using EUR reference from Pan-UKB [51ms]
✔ Reading LD Scores [252ms]                                                                                     
✔ Reading weights [159ms]                                                                                       
✔ Reading M [39ms]                                                                                                
✔ Reading summary statistics for 'COPD' from dataframe [16ms]
ℹ 1082885/11831889 SNPs remain after merging 'COPD' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 455.449 from 'COPD'; 1082885 SNPs remain
✔ Merging 'COPD' with LD-score files [9.7s]
✔ Reading summary statistics for 'Smoking' from dataframe [14ms]
ℹ 1093765/8683163 SNPs remain after merging 'Smoking' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 80 from 'Smoking'; 1093765 SNPs remain
✔ Merging 'Smoking' with LD-score files [5.6s]
✔ Reading summary statistics [15.4s]
✔ Estimating heritability for 'COPD' [144ms]
✔ Estimating genetic covariance for for 'COPD' and 'Smoking' [1.5s]
! Your genetic covariance matrix includes traits estimated to have a negative heritability.
Error: object 'S_Stand' not foundoking'
✖ Estimating heritability for 'Smoking' [469ms]

**Comment by mglev1n** [comment]
That error suggests there is a problem with your GWAS summary statistics (eg. using a small, underpowered GWAS without significant trait heritability), and comes from the `GenomicSEM` package (https://github.com/GenomicSEM/GenomicSEM/) which `ldscr` leverages for calculating heritability and genetic correlations.
