### ISSUE TITLE
Ask for your help

### ISSUE THREAD

**Issue by hyjyd** [mglev1n/ldscr#19]
I am a university student from China and have encountered an error while using your R package. Could you please provide some guidance on how to resolve it? Thank you.
 [1] "SNP"                    "other_allele.exposure"  "effect_allele.exposure" "beta.exposure"          "se.exposure"           
 [6] "exposure"               "mr_keep.exposure"       "pval.exposure"          "pval_origin.exposure"   "id.exposure"           
[11] "eaf.exposure"           "samplesize.exposure"   
✔ No ancestry specified, checking for user-specified `ld` and `wld` [28ms]
✔ Reading LD Scores [684ms]                                                                                                         
✔ Reading weights [683ms]                                                                                                           
✔ Reading M [72ms]                                                                                                                    
✔ Reading summary statistics for '0176.txt.gz' from dataframe [28ms]
ℹ 1288230/17078548 SNPs remain after merging '0176.txt.gz' with LD-score files
ℹ Removed 0 SNPs with Chi^2 > 80 from '0176.txt.gz'; 1288230 SNPs remain
✔ Merging '0176.txt.gz' with LD-score files [28.2s]
✔ Reading summary statistics for 'T2D' from dataframe [28ms]
ℹ 1281623/19682557 SNPs remain after merging 'T2D' with LD-score files
ℹ Removed 7 SNPs with Chi^2 > 400.197 from 'T2D'; 1281616 SNPs remain
✔ Merging 'T2D' with LD-score files [26.7s]
✔ Reading summary statistics [55.1s]
✔ Estimating heritability for '0176.txt.gz' [213ms]
✔ Estimating genetic covariance for for '0176.txt.gz' and 'T2D' [2.4s]
! Your genetic covariance matrix includes traits estimated to have a negative heritability.
✖ Estimating heritability for 'T2D' [232ms]
Error : 找不到对象'S_Stand'
错误于LDSC_res[["h2"]]: 下标出界

**Comment by mglev1n** [comment]
See: https://github.com/mglev1n/ldscr/issues/8
