### ISSUE TITLE
Format of raw data

### ISSUE THREAD

**Issue by senmingjiu** [mglev1n/ldscr#5]
Hi, 
if I want to do LDSC analysis with this R package of yours, should I organize the raw data into a certain form? What should the form be like? Thank you for your R package.

**Comment by mglev1n** [comment]
The format of the raw data (provided to the `ldsc_h2` and `ldsc_rg` functions) should be either dataframes or text files, which Must contain at least columns named `SNP` (rsid), `A1` (effect allele), `A2` (non-effect allele), `N` (total sample size) and `Z` (Z-score).

- https://mglev1n.github.io/ldscr/reference/ldsc_h2.html
- https://mglev1n.github.io/ldscr/reference/ldsc_rg.html
