### ISSUE TITLE
when trying to use the ldscr analyse, I met the bug.

### ISSUE THREAD

**Issue by owo12138** [mglev1n/ldscr#7]
![image](https://github.com/mglev1n/ldscr/assets/115405260/2237d5b0-7f50-4c52-bd39-e8c5dca028d3)

**Comment by owo12138** [comment]
If encountering this bug, does it mean there's an issue with my data? How should I self-inspect my data and then improve it?

**Comment by mglev1n** [comment]
Both the datasets seem to be very old GWAS (more than a decade old), and include relatively small sample sizes. The error indicates that at least one of the traits has negative heritability, and I suspect this lack of heritability is creating a problem when trying to estimate cross-trait heritability. I'd recommend trying to use the original ldsc package (https://github.com/bulik/ldsc), and more broadly using more contemporary/larger GWAS which better capture the heritability of the underlying traits you're interested in.
